import { buildJobSourceConfig } from "@/lib/jobs/source-config";

type TrustedSourceSeed = {
  name: string;
  sourceType:
    | "government-source"
    | "company-career-page"
    | "employer-feed"
    | "api-feed";
  fetchMethod: "government" | "html" | "lever" | "greenhouse" | "api";
  sourceUrl: string;
  companyName: string;
  industry: string;
  defaultCity: string;
  defaultState: string;
  allowAutoFetch: boolean;
  isActive: boolean;
  notes: string;
};

const GOVERNMENT_NOTE =
  "Official source. Safe to keep active. Review extracted results before publishing.";
const COMPANY_NOTE =
  "Trusted company career page. Added as approved source, but manual review is recommended before enabling auto fetch at scale.";
const EMPLOYER_FEED_NOTE =
  "Trusted public employer feed. Review extracted results before enabling auto fetch broadly.";
const API_FEED_NOTE =
  "Trusted public jobs API feed. Keep review-first and verify parser quality before scaling.";

export const TRUSTED_SOURCE_PACK: TrustedSourceSeed[] = [
  {
    name: "National Career Service",
    sourceType: "government-source",
    fetchMethod: "government",
    sourceUrl: "https://www.ncs.gov.in/",
    companyName: "National Career Service",
    industry: "Government",
    defaultCity: "New Delhi",
    defaultState: "Delhi",
    allowAutoFetch: true,
    isActive: true,
    notes: GOVERNMENT_NOTE,
  },
  {
    name: "UPSC Online",
    sourceType: "government-source",
    fetchMethod: "government",
    sourceUrl: "https://upsconline.nic.in/",
    companyName: "Union Public Service Commission",
    industry: "Government",
    defaultCity: "New Delhi",
    defaultState: "Delhi",
    allowAutoFetch: true,
    isActive: true,
    notes: GOVERNMENT_NOTE,
  },
  {
    name: "Staff Selection Commission",
    sourceType: "government-source",
    fetchMethod: "government",
    sourceUrl: "https://ssc.gov.in/",
    companyName: "Staff Selection Commission",
    industry: "Government",
    defaultCity: "New Delhi",
    defaultState: "Delhi",
    allowAutoFetch: true,
    isActive: true,
    notes: GOVERNMENT_NOTE,
  },
  {
    name: "IBPS",
    sourceType: "government-source",
    fetchMethod: "government",
    sourceUrl: "https://www.ibps.in/",
    companyName: "Institute of Banking Personnel Selection",
    industry: "Government Banking Recruitment",
    defaultCity: "Mumbai",
    defaultState: "Maharashtra",
    allowAutoFetch: true,
    isActive: true,
    notes: GOVERNMENT_NOTE,
  },
  {
    name: "SBI Careers",
    sourceType: "government-source",
    fetchMethod: "government",
    sourceUrl: "https://sbi.co.in/web/careers",
    companyName: "State Bank of India",
    industry: "Public Sector Banking",
    defaultCity: "Mumbai",
    defaultState: "Maharashtra",
    allowAutoFetch: true,
    isActive: true,
    notes: GOVERNMENT_NOTE,
  },
  {
    name: "RBI Opportunities",
    sourceType: "government-source",
    fetchMethod: "government",
    sourceUrl: "https://opportunities.rbi.org.in/",
    companyName: "Reserve Bank of India",
    industry: "Central Banking",
    defaultCity: "Mumbai",
    defaultState: "Maharashtra",
    allowAutoFetch: true,
    isActive: true,
    notes: GOVERNMENT_NOTE,
  },
  {
    name: "Railway Recruitment Boards",
    sourceType: "government-source",
    fetchMethod: "government",
    sourceUrl: "https://www.rrbcdg.gov.in/",
    companyName: "Railway Recruitment Boards",
    industry: "Railways",
    defaultCity: "Chandigarh",
    defaultState: "Chandigarh",
    allowAutoFetch: true,
    isActive: true,
    notes: GOVERNMENT_NOTE,
  },
  {
    name: "DRDO Careers",
    sourceType: "government-source",
    fetchMethod: "government",
    sourceUrl: "https://www.drdo.gov.in/drdo/careers",
    companyName: "DRDO",
    industry: "Defence Research",
    defaultCity: "New Delhi",
    defaultState: "Delhi",
    allowAutoFetch: true,
    isActive: true,
    notes: GOVERNMENT_NOTE,
  },
  {
    name: "ISRO Careers",
    sourceType: "government-source",
    fetchMethod: "government",
    sourceUrl: "https://www.isro.gov.in/Careers.html",
    companyName: "ISRO",
    industry: "Space Research",
    defaultCity: "Bengaluru",
    defaultState: "Karnataka",
    allowAutoFetch: true,
    isActive: true,
    notes: GOVERNMENT_NOTE,
  },
  {
    name: "BARC Recruitment",
    sourceType: "government-source",
    fetchMethod: "government",
    sourceUrl: "https://recruit.barc.gov.in/",
    companyName: "BARC",
    industry: "Atomic Research",
    defaultCity: "Mumbai",
    defaultState: "Maharashtra",
    allowAutoFetch: true,
    isActive: true,
    notes: GOVERNMENT_NOTE,
  },
  {
    name: "BEL Careers",
    sourceType: "government-source",
    fetchMethod: "government",
    sourceUrl: "https://bel-india.in/careers/",
    companyName: "Bharat Electronics Limited",
    industry: "Defence Electronics",
    defaultCity: "Bengaluru",
    defaultState: "Karnataka",
    allowAutoFetch: true,
    isActive: true,
    notes: GOVERNMENT_NOTE,
  },
  {
    name: "HAL Careers",
    sourceType: "government-source",
    fetchMethod: "government",
    sourceUrl: "https://hal-india.co.in/career",
    companyName: "Hindustan Aeronautics Limited",
    industry: "Aerospace",
    defaultCity: "Bengaluru",
    defaultState: "Karnataka",
    allowAutoFetch: true,
    isActive: true,
    notes: GOVERNMENT_NOTE,
  },
  {
    name: "ECIL Careers",
    sourceType: "government-source",
    fetchMethod: "government",
    sourceUrl: "https://www.ecil.co.in/jobs.html",
    companyName: "Electronics Corporation of India Limited",
    industry: "Electronics",
    defaultCity: "Hyderabad",
    defaultState: "Telangana",
    allowAutoFetch: true,
    isActive: true,
    notes: GOVERNMENT_NOTE,
  },
  {
    name: "NTPC Careers",
    sourceType: "government-source",
    fetchMethod: "government",
    sourceUrl: "https://careers.ntpc.co.in/",
    companyName: "NTPC",
    industry: "Power",
    defaultCity: "New Delhi",
    defaultState: "Delhi",
    allowAutoFetch: true,
    isActive: true,
    notes: GOVERNMENT_NOTE,
  },
  {
    name: "POWERGRID Jobs",
    sourceType: "government-source",
    fetchMethod: "government",
    sourceUrl: "https://www.powergrid.in/job-opportunities",
    companyName: "Power Grid Corporation of India",
    industry: "Power Transmission",
    defaultCity: "Gurugram",
    defaultState: "Haryana",
    allowAutoFetch: true,
    isActive: true,
    notes: GOVERNMENT_NOTE,
  },
  {
    name: "NHPC Careers",
    sourceType: "government-source",
    fetchMethod: "government",
    sourceUrl: "https://www.nhpcindia.com/career.htm",
    companyName: "NHPC",
    industry: "Hydropower",
    defaultCity: "Faridabad",
    defaultState: "Haryana",
    allowAutoFetch: true,
    isActive: true,
    notes: GOVERNMENT_NOTE,
  },
  {
    name: "NPCIL Careers",
    sourceType: "government-source",
    fetchMethod: "government",
    sourceUrl: "https://www.npcilcareers.co.in/",
    companyName: "NPCIL",
    industry: "Nuclear Power",
    defaultCity: "Mumbai",
    defaultState: "Maharashtra",
    allowAutoFetch: true,
    isActive: true,
    notes: GOVERNMENT_NOTE,
  },
  {
    name: "ONGC Careers",
    sourceType: "government-source",
    fetchMethod: "government",
    sourceUrl: "https://ongcindia.com/web/eng/career",
    companyName: "ONGC",
    industry: "Oil and Gas",
    defaultCity: "Dehradun",
    defaultState: "Uttarakhand",
    allowAutoFetch: true,
    isActive: true,
    notes: GOVERNMENT_NOTE,
  },
  {
    name: "IOCL Jobs",
    sourceType: "government-source",
    fetchMethod: "government",
    sourceUrl: "https://iocl.com/latest-job-opening",
    companyName: "Indian Oil Corporation",
    industry: "Oil and Gas",
    defaultCity: "New Delhi",
    defaultState: "Delhi",
    allowAutoFetch: true,
    isActive: true,
    notes: GOVERNMENT_NOTE,
  },
  {
    name: "HPCL Careers",
    sourceType: "government-source",
    fetchMethod: "government",
    sourceUrl: "https://www.hindustanpetroleum.com/hpcareers/current_openings",
    companyName: "Hindustan Petroleum",
    industry: "Oil and Gas",
    defaultCity: "Mumbai",
    defaultState: "Maharashtra",
    allowAutoFetch: true,
    isActive: true,
    notes: GOVERNMENT_NOTE,
  },
  {
    name: "BPCL Careers",
    sourceType: "government-source",
    fetchMethod: "government",
    sourceUrl: "https://www.bharatpetroleum.in/Careers/Job-Openings.aspx",
    companyName: "Bharat Petroleum",
    industry: "Oil and Gas",
    defaultCity: "Mumbai",
    defaultState: "Maharashtra",
    allowAutoFetch: true,
    isActive: true,
    notes: GOVERNMENT_NOTE,
  },
  {
    name: "GAIL Careers",
    sourceType: "government-source",
    fetchMethod: "government",
    sourceUrl: "https://gailonline.com/CRCurrentOpening.html",
    companyName: "GAIL",
    industry: "Natural Gas",
    defaultCity: "New Delhi",
    defaultState: "Delhi",
    allowAutoFetch: true,
    isActive: true,
    notes: GOVERNMENT_NOTE,
  },
  {
    name: "SAIL Careers",
    sourceType: "government-source",
    fetchMethod: "government",
    sourceUrl: "https://www.sail.co.in/en/careers",
    companyName: "Steel Authority of India",
    industry: "Steel",
    defaultCity: "New Delhi",
    defaultState: "Delhi",
    allowAutoFetch: true,
    isActive: true,
    notes: GOVERNMENT_NOTE,
  },
  {
    name: "Coal India Careers",
    sourceType: "government-source",
    fetchMethod: "government",
    sourceUrl: "https://www.coalindia.in/career-cbi/",
    companyName: "Coal India",
    industry: "Mining",
    defaultCity: "Kolkata",
    defaultState: "West Bengal",
    allowAutoFetch: true,
    isActive: true,
    notes: GOVERNMENT_NOTE,
  },
  {
    name: "AAI Recruitment",
    sourceType: "government-source",
    fetchMethod: "government",
    sourceUrl: "https://www.aai.aero/en/careers/recruitment",
    companyName: "Airports Authority of India",
    industry: "Aviation",
    defaultCity: "New Delhi",
    defaultState: "Delhi",
    allowAutoFetch: true,
    isActive: true,
    notes: GOVERNMENT_NOTE,
  },
  {
    name: "FCI Recruitment",
    sourceType: "government-source",
    fetchMethod: "government",
    sourceUrl: "https://fci.gov.in/recruitments.php",
    companyName: "Food Corporation of India",
    industry: "Food Logistics",
    defaultCity: "New Delhi",
    defaultState: "Delhi",
    allowAutoFetch: true,
    isActive: true,
    notes: GOVERNMENT_NOTE,
  },
  {
    name: "LIC Careers",
    sourceType: "government-source",
    fetchMethod: "government",
    sourceUrl: "https://licindia.in/web/guest/careers",
    companyName: "Life Insurance Corporation of India",
    industry: "Insurance",
    defaultCity: "Mumbai",
    defaultState: "Maharashtra",
    allowAutoFetch: true,
    isActive: true,
    notes: GOVERNMENT_NOTE,
  },
  {
    name: "NIACL Recruitment",
    sourceType: "government-source",
    fetchMethod: "government",
    sourceUrl: "https://www.newindia.co.in/portal/recruitment",
    companyName: "New India Assurance",
    industry: "Insurance",
    defaultCity: "Mumbai",
    defaultState: "Maharashtra",
    allowAutoFetch: true,
    isActive: true,
    notes: GOVERNMENT_NOTE,
  },
  {
    name: "UIIC Recruitment",
    sourceType: "government-source",
    fetchMethod: "government",
    sourceUrl: "https://uiic.co.in/recruitment",
    companyName: "United India Insurance",
    industry: "Insurance",
    defaultCity: "Chennai",
    defaultState: "Tamil Nadu",
    allowAutoFetch: true,
    isActive: true,
    notes: GOVERNMENT_NOTE,
  },
  {
    name: "ESIC Recruitment",
    sourceType: "government-source",
    fetchMethod: "government",
    sourceUrl: "https://www.esic.gov.in/recruitments",
    companyName: "Employees' State Insurance Corporation",
    industry: "Government",
    defaultCity: "New Delhi",
    defaultState: "Delhi",
    allowAutoFetch: true,
    isActive: true,
    notes: GOVERNMENT_NOTE,
  },
  {
    name: "DSSSB",
    sourceType: "government-source",
    fetchMethod: "government",
    sourceUrl: "https://dsssb.delhi.gov.in/",
    companyName: "Delhi Subordinate Services Selection Board",
    industry: "Government",
    defaultCity: "New Delhi",
    defaultState: "Delhi",
    allowAutoFetch: true,
    isActive: true,
    notes: GOVERNMENT_NOTE,
  },
  {
    name: "KVS Recruitment",
    sourceType: "government-source",
    fetchMethod: "government",
    sourceUrl: "https://kvsangathan.nic.in/en/recruitment/",
    companyName: "Kendriya Vidyalaya Sangathan",
    industry: "Education",
    defaultCity: "New Delhi",
    defaultState: "Delhi",
    allowAutoFetch: true,
    isActive: true,
    notes: GOVERNMENT_NOTE,
  },
  {
    name: "NVS Recruitment",
    sourceType: "government-source",
    fetchMethod: "government",
    sourceUrl: "https://navodaya.gov.in/nvs/en/Home1/Recruitment/",
    companyName: "Navodaya Vidyalaya Samiti",
    industry: "Education",
    defaultCity: "Noida",
    defaultState: "Uttar Pradesh",
    allowAutoFetch: true,
    isActive: true,
    notes: GOVERNMENT_NOTE,
  },
  {
    name: "Delhi Police Recruitment",
    sourceType: "government-source",
    fetchMethod: "government",
    sourceUrl: "https://delhipolice.gov.in/recruitment",
    companyName: "Delhi Police",
    industry: "Police",
    defaultCity: "New Delhi",
    defaultState: "Delhi",
    allowAutoFetch: true,
    isActive: true,
    notes: GOVERNMENT_NOTE,
  },
  {
    name: "BPSC",
    sourceType: "government-source",
    fetchMethod: "government",
    sourceUrl: "https://bpsc.bihar.gov.in/",
    companyName: "Bihar Public Service Commission",
    industry: "Government",
    defaultCity: "Patna",
    defaultState: "Bihar",
    allowAutoFetch: true,
    isActive: true,
    notes: GOVERNMENT_NOTE,
  },
  {
    name: "UPPSC",
    sourceType: "government-source",
    fetchMethod: "government",
    sourceUrl: "https://uppsc.up.nic.in/",
    companyName: "Uttar Pradesh Public Service Commission",
    industry: "Government",
    defaultCity: "Prayagraj",
    defaultState: "Uttar Pradesh",
    allowAutoFetch: true,
    isActive: true,
    notes: GOVERNMENT_NOTE,
  },
  {
    name: "RPSC",
    sourceType: "government-source",
    fetchMethod: "government",
    sourceUrl: "https://rpsc.rajasthan.gov.in/",
    companyName: "Rajasthan Public Service Commission",
    industry: "Government",
    defaultCity: "Ajmer",
    defaultState: "Rajasthan",
    allowAutoFetch: true,
    isActive: true,
    notes: GOVERNMENT_NOTE,
  },
  {
    name: "HSSC",
    sourceType: "government-source",
    fetchMethod: "government",
    sourceUrl: "https://www.hssc.gov.in/",
    companyName: "Haryana Staff Selection Commission",
    industry: "Government",
    defaultCity: "Panchkula",
    defaultState: "Haryana",
    allowAutoFetch: true,
    isActive: true,
    notes: GOVERNMENT_NOTE,
  },
  {
    name: "Punjab Police Recruitment",
    sourceType: "government-source",
    fetchMethod: "government",
    sourceUrl: "https://punjabpolice.gov.in/Recruitment",
    companyName: "Punjab Police",
    industry: "Police",
    defaultCity: "Chandigarh",
    defaultState: "Punjab",
    allowAutoFetch: true,
    isActive: true,
    notes: GOVERNMENT_NOTE,
  },
  {
    name: "OPSC",
    sourceType: "government-source",
    fetchMethod: "government",
    sourceUrl: "https://www.opsc.gov.in/Public/OPSC/Default.aspx",
    companyName: "Odisha Public Service Commission",
    industry: "Government",
    defaultCity: "Cuttack",
    defaultState: "Odisha",
    allowAutoFetch: true,
    isActive: true,
    notes: GOVERNMENT_NOTE,
  },
  {
    name: "MPSC",
    sourceType: "government-source",
    fetchMethod: "government",
    sourceUrl: "https://mpsc.gov.in/",
    companyName: "Maharashtra Public Service Commission",
    industry: "Government",
    defaultCity: "Mumbai",
    defaultState: "Maharashtra",
    allowAutoFetch: true,
    isActive: true,
    notes: GOVERNMENT_NOTE,
  },
  {
    name: "TNPSC",
    sourceType: "government-source",
    fetchMethod: "government",
    sourceUrl: "https://www.tnpsc.gov.in/",
    companyName: "Tamil Nadu Public Service Commission",
    industry: "Government",
    defaultCity: "Chennai",
    defaultState: "Tamil Nadu",
    allowAutoFetch: true,
    isActive: true,
    notes: GOVERNMENT_NOTE,
  },
  {
    name: "APPSC",
    sourceType: "government-source",
    fetchMethod: "government",
    sourceUrl: "https://psc.ap.gov.in/",
    companyName: "Andhra Pradesh Public Service Commission",
    industry: "Government",
    defaultCity: "Vijayawada",
    defaultState: "Andhra Pradesh",
    allowAutoFetch: true,
    isActive: true,
    notes: GOVERNMENT_NOTE,
  },
  {
    name: "TSPSC",
    sourceType: "government-source",
    fetchMethod: "government",
    sourceUrl: "https://www.tspsc.gov.in/",
    companyName: "Telangana State Public Service Commission",
    industry: "Government",
    defaultCity: "Hyderabad",
    defaultState: "Telangana",
    allowAutoFetch: true,
    isActive: true,
    notes: GOVERNMENT_NOTE,
  },
  {
    name: "PPSC",
    sourceType: "government-source",
    fetchMethod: "government",
    sourceUrl: "https://ppsc.gov.in/",
    companyName: "Punjab Public Service Commission",
    industry: "Government",
    defaultCity: "Patiala",
    defaultState: "Punjab",
    allowAutoFetch: true,
    isActive: true,
    notes: GOVERNMENT_NOTE,
  },
  {
    name: "WBPSC",
    sourceType: "government-source",
    fetchMethod: "government",
    sourceUrl: "https://psc.wb.gov.in/",
    companyName: "West Bengal Public Service Commission",
    industry: "Government",
    defaultCity: "Kolkata",
    defaultState: "West Bengal",
    allowAutoFetch: true,
    isActive: true,
    notes: GOVERNMENT_NOTE,
  },
  {
    name: "GPSC",
    sourceType: "government-source",
    fetchMethod: "government",
    sourceUrl: "https://gpsc.gujarat.gov.in/",
    companyName: "Gujarat Public Service Commission",
    industry: "Government",
    defaultCity: "Gandhinagar",
    defaultState: "Gujarat",
    allowAutoFetch: true,
    isActive: true,
    notes: GOVERNMENT_NOTE,
  },
  {
    name: "MPPSC",
    sourceType: "government-source",
    fetchMethod: "government",
    sourceUrl: "https://mppsc.mp.gov.in/",
    companyName: "Madhya Pradesh Public Service Commission",
    industry: "Government",
    defaultCity: "Indore",
    defaultState: "Madhya Pradesh",
    allowAutoFetch: true,
    isActive: true,
    notes: GOVERNMENT_NOTE,
  },
  {
    name: "JKPSC",
    sourceType: "government-source",
    fetchMethod: "government",
    sourceUrl: "https://jkpsc.nic.in/",
    companyName: "Jammu and Kashmir Public Service Commission",
    industry: "Government",
    defaultCity: "Jammu",
    defaultState: "Jammu and Kashmir",
    allowAutoFetch: true,
    isActive: true,
    notes: GOVERNMENT_NOTE,
  },
  {
    name: "TCS Careers",
    sourceType: "company-career-page",
    fetchMethod: "html",
    sourceUrl: "https://www.tcs.com/careers",
    companyName: "Tata Consultancy Services",
    industry: "IT Services",
    defaultCity: "Bengaluru",
    defaultState: "Karnataka",
    allowAutoFetch: false,
    isActive: true,
    notes: COMPANY_NOTE,
  },
  {
    name: "Infosys Careers",
    sourceType: "company-career-page",
    fetchMethod: "html",
    sourceUrl: "https://www.infosys.com/careers.html",
    companyName: "Infosys",
    industry: "IT Services",
    defaultCity: "Bengaluru",
    defaultState: "Karnataka",
    allowAutoFetch: false,
    isActive: true,
    notes: COMPANY_NOTE,
  },
  {
    name: "Wipro Careers",
    sourceType: "company-career-page",
    fetchMethod: "html",
    sourceUrl: "https://careers.wipro.com/",
    companyName: "Wipro",
    industry: "IT Services",
    defaultCity: "Bengaluru",
    defaultState: "Karnataka",
    allowAutoFetch: false,
    isActive: true,
    notes: COMPANY_NOTE,
  },
  {
    name: "HCLTech Careers",
    sourceType: "company-career-page",
    fetchMethod: "html",
    sourceUrl: "https://www.hcltech.com/careers",
    companyName: "HCLTech",
    industry: "IT Services",
    defaultCity: "Noida",
    defaultState: "Uttar Pradesh",
    allowAutoFetch: false,
    isActive: true,
    notes: COMPANY_NOTE,
  },
  {
    name: "Tech Mahindra Careers",
    sourceType: "company-career-page",
    fetchMethod: "html",
    sourceUrl: "https://careers.techmahindra.com/",
    companyName: "Tech Mahindra",
    industry: "IT Services",
    defaultCity: "Pune",
    defaultState: "Maharashtra",
    allowAutoFetch: false,
    isActive: true,
    notes: COMPANY_NOTE,
  },
  {
    name: "LTIMindtree Careers",
    sourceType: "company-career-page",
    fetchMethod: "html",
    sourceUrl: "https://careers.ltimindtree.com/",
    companyName: "LTIMindtree",
    industry: "IT Services",
    defaultCity: "Mumbai",
    defaultState: "Maharashtra",
    allowAutoFetch: false,
    isActive: true,
    notes: COMPANY_NOTE,
  },
  {
    name: "Accenture Careers India",
    sourceType: "company-career-page",
    fetchMethod: "html",
    sourceUrl: "https://www.accenture.com/in-en/careers",
    companyName: "Accenture",
    industry: "Consulting",
    defaultCity: "Bengaluru",
    defaultState: "Karnataka",
    allowAutoFetch: false,
    isActive: true,
    notes: COMPANY_NOTE,
  },
  {
    name: "Cognizant Careers",
    sourceType: "company-career-page",
    fetchMethod: "html",
    sourceUrl: "https://careers.cognizant.com/in/en",
    companyName: "Cognizant",
    industry: "IT Services",
    defaultCity: "Chennai",
    defaultState: "Tamil Nadu",
    allowAutoFetch: false,
    isActive: true,
    notes: COMPANY_NOTE,
  },
  {
    name: "IBM Careers India",
    sourceType: "company-career-page",
    fetchMethod: "html",
    sourceUrl: "https://www.ibm.com/careers/search?field_keyword_08[0]=India",
    companyName: "IBM",
    industry: "Technology",
    defaultCity: "Bengaluru",
    defaultState: "Karnataka",
    allowAutoFetch: false,
    isActive: true,
    notes: COMPANY_NOTE,
  },
  {
    name: "Capgemini Careers",
    sourceType: "company-career-page",
    fetchMethod: "html",
    sourceUrl: "https://www.capgemini.com/careers/",
    companyName: "Capgemini",
    industry: "Consulting",
    defaultCity: "Mumbai",
    defaultState: "Maharashtra",
    allowAutoFetch: false,
    isActive: true,
    notes: COMPANY_NOTE,
  },
  {
    name: "Deloitte India Careers",
    sourceType: "company-career-page",
    fetchMethod: "html",
    sourceUrl: "https://www2.deloitte.com/in/en/careers.html",
    companyName: "Deloitte India",
    industry: "Consulting",
    defaultCity: "Gurugram",
    defaultState: "Haryana",
    allowAutoFetch: false,
    isActive: true,
    notes: COMPANY_NOTE,
  },
  {
    name: "EY India Careers",
    sourceType: "company-career-page",
    fetchMethod: "html",
    sourceUrl: "https://www.ey.com/en_in/careers",
    companyName: "EY India",
    industry: "Consulting",
    defaultCity: "Bengaluru",
    defaultState: "Karnataka",
    allowAutoFetch: false,
    isActive: true,
    notes: COMPANY_NOTE,
  },
  {
    name: "PwC India Careers",
    sourceType: "company-career-page",
    fetchMethod: "html",
    sourceUrl: "https://www.pwc.in/careers.html",
    companyName: "PwC India",
    industry: "Consulting",
    defaultCity: "Gurugram",
    defaultState: "Haryana",
    allowAutoFetch: false,
    isActive: true,
    notes: COMPANY_NOTE,
  },
  {
    name: "KPMG India Careers",
    sourceType: "company-career-page",
    fetchMethod: "html",
    sourceUrl: "https://kpmg.com/in/en/home/careers.html",
    companyName: "KPMG India",
    industry: "Consulting",
    defaultCity: "Gurugram",
    defaultState: "Haryana",
    allowAutoFetch: false,
    isActive: true,
    notes: COMPANY_NOTE,
  },
  {
    name: "Oracle India Careers",
    sourceType: "company-career-page",
    fetchMethod: "html",
    sourceUrl: "https://www.oracle.com/in/careers/",
    companyName: "Oracle",
    industry: "Technology",
    defaultCity: "Bengaluru",
    defaultState: "Karnataka",
    allowAutoFetch: false,
    isActive: true,
    notes: COMPANY_NOTE,
  },
  {
    name: "SAP India Careers",
    sourceType: "company-career-page",
    fetchMethod: "html",
    sourceUrl: "https://www.sap.com/india/about/careers.html",
    companyName: "SAP",
    industry: "Technology",
    defaultCity: "Bengaluru",
    defaultState: "Karnataka",
    allowAutoFetch: false,
    isActive: true,
    notes: COMPANY_NOTE,
  },
  {
    name: "Microsoft Careers",
    sourceType: "company-career-page",
    fetchMethod: "html",
    sourceUrl: "https://careers.microsoft.com/v2/global/en/home.html",
    companyName: "Microsoft",
    industry: "Technology",
    defaultCity: "Hyderabad",
    defaultState: "Telangana",
    allowAutoFetch: false,
    isActive: true,
    notes: COMPANY_NOTE,
  },
  {
    name: "Google Careers India",
    sourceType: "company-career-page",
    fetchMethod: "html",
    sourceUrl: "https://www.google.com/about/careers/applications/jobs/results/?location=India",
    companyName: "Google",
    industry: "Technology",
    defaultCity: "Bengaluru",
    defaultState: "Karnataka",
    allowAutoFetch: false,
    isActive: true,
    notes: COMPANY_NOTE,
  },
  {
    name: "Amazon Jobs India",
    sourceType: "company-career-page",
    fetchMethod: "html",
    sourceUrl: "https://www.amazon.jobs/en/locations/india",
    companyName: "Amazon",
    industry: "E-commerce",
    defaultCity: "Bengaluru",
    defaultState: "Karnataka",
    allowAutoFetch: false,
    isActive: true,
    notes: COMPANY_NOTE,
  },
  {
    name: "Flipkart Careers",
    sourceType: "company-career-page",
    fetchMethod: "html",
    sourceUrl: "https://www.flipkartcareers.com/#!/joblist",
    companyName: "Flipkart",
    industry: "E-commerce",
    defaultCity: "Bengaluru",
    defaultState: "Karnataka",
    allowAutoFetch: false,
    isActive: true,
    notes: COMPANY_NOTE,
  },
  {
    name: "Zoho Careers",
    sourceType: "company-career-page",
    fetchMethod: "html",
    sourceUrl: "https://www.zoho.com/careers/",
    companyName: "Zoho",
    industry: "Technology",
    defaultCity: "Chennai",
    defaultState: "Tamil Nadu",
    allowAutoFetch: false,
    isActive: true,
    notes: COMPANY_NOTE,
  },
  {
    name: "Freshworks Careers",
    sourceType: "company-career-page",
    fetchMethod: "html",
    sourceUrl: "https://www.freshworks.com/company/careers/",
    companyName: "Freshworks",
    industry: "SaaS",
    defaultCity: "Chennai",
    defaultState: "Tamil Nadu",
    allowAutoFetch: false,
    isActive: true,
    notes: COMPANY_NOTE,
  },
  {
    name: "Paytm Careers",
    sourceType: "company-career-page",
    fetchMethod: "html",
    sourceUrl: "https://paytm.com/careers/",
    companyName: "Paytm",
    industry: "Fintech",
    defaultCity: "Noida",
    defaultState: "Uttar Pradesh",
    allowAutoFetch: false,
    isActive: true,
    notes: COMPANY_NOTE,
  },
  {
    name: "PhonePe Careers",
    sourceType: "company-career-page",
    fetchMethod: "html",
    sourceUrl: "https://www.phonepe.com/careers/",
    companyName: "PhonePe",
    industry: "Fintech",
    defaultCity: "Bengaluru",
    defaultState: "Karnataka",
    allowAutoFetch: false,
    isActive: true,
    notes: COMPANY_NOTE,
  },
  {
    name: "Razorpay Jobs",
    sourceType: "company-career-page",
    fetchMethod: "html",
    sourceUrl: "https://razorpay.com/jobs/",
    companyName: "Razorpay",
    industry: "Fintech",
    defaultCity: "Bengaluru",
    defaultState: "Karnataka",
    allowAutoFetch: false,
    isActive: true,
    notes: COMPANY_NOTE,
  },
  {
    name: "Swiggy Careers",
    sourceType: "company-career-page",
    fetchMethod: "html",
    sourceUrl: "https://careers.swiggy.com/",
    companyName: "Swiggy",
    industry: "Consumer Internet",
    defaultCity: "Bengaluru",
    defaultState: "Karnataka",
    allowAutoFetch: false,
    isActive: true,
    notes: COMPANY_NOTE,
  },
  {
    name: "Zomato Careers",
    sourceType: "company-career-page",
    fetchMethod: "html",
    sourceUrl: "https://www.zomato.com/careers",
    companyName: "Zomato",
    industry: "Consumer Internet",
    defaultCity: "Gurugram",
    defaultState: "Haryana",
    allowAutoFetch: false,
    isActive: true,
    notes: COMPANY_NOTE,
  },
  {
    name: "Reliance Industries Careers",
    sourceType: "company-career-page",
    fetchMethod: "html",
    sourceUrl: "https://www.ril.com/Careers",
    companyName: "Reliance Industries",
    industry: "Conglomerate",
    defaultCity: "Mumbai",
    defaultState: "Maharashtra",
    allowAutoFetch: false,
    isActive: true,
    notes: COMPANY_NOTE,
  },
  {
    name: "Tata Steel Careers",
    sourceType: "company-career-page",
    fetchMethod: "html",
    sourceUrl: "https://www.tatasteel.com/careers/",
    companyName: "Tata Steel",
    industry: "Steel",
    defaultCity: "Jamshedpur",
    defaultState: "Jharkhand",
    allowAutoFetch: false,
    isActive: true,
    notes: COMPANY_NOTE,
  },
  {
    name: "Adani Careers",
    sourceType: "company-career-page",
    fetchMethod: "html",
    sourceUrl: "https://careers.adani.com/",
    companyName: "Adani Group",
    industry: "Conglomerate",
    defaultCity: "Ahmedabad",
    defaultState: "Gujarat",
    allowAutoFetch: false,
    isActive: true,
    notes: COMPANY_NOTE,
  },
  {
    name: "Larsen & Toubro Careers",
    sourceType: "company-career-page",
    fetchMethod: "html",
    sourceUrl: "https://larsentoubrocareers.peoplestrong.com/home",
    companyName: "Larsen & Toubro",
    industry: "Engineering",
    defaultCity: "Mumbai",
    defaultState: "Maharashtra",
    allowAutoFetch: false,
    isActive: true,
    notes: COMPANY_NOTE,
  },
  {
    name: "Mahindra Group Careers",
    sourceType: "company-career-page",
    fetchMethod: "html",
    sourceUrl: "https://jobs.mahindragroup.com/",
    companyName: "Mahindra Group",
    industry: "Conglomerate",
    defaultCity: "Mumbai",
    defaultState: "Maharashtra",
    allowAutoFetch: false,
    isActive: true,
    notes: COMPANY_NOTE,
  },
  {
    name: "Tata Motors Careers",
    sourceType: "company-career-page",
    fetchMethod: "html",
    sourceUrl: "https://careers.tatamotors.com/",
    companyName: "Tata Motors",
    industry: "Automotive",
    defaultCity: "Pune",
    defaultState: "Maharashtra",
    allowAutoFetch: false,
    isActive: true,
    notes: COMPANY_NOTE,
  },
  {
    name: "Maruti Suzuki Careers",
    sourceType: "company-career-page",
    fetchMethod: "html",
    sourceUrl: "https://www.marutisuzuki.com/corporate/careers",
    companyName: "Maruti Suzuki",
    industry: "Automotive",
    defaultCity: "Gurugram",
    defaultState: "Haryana",
    allowAutoFetch: false,
    isActive: true,
    notes: COMPANY_NOTE,
  },
  {
    name: "HDFC Bank Careers",
    sourceType: "company-career-page",
    fetchMethod: "html",
    sourceUrl: "https://www.hdfcbank.com/personal/about-us/careers",
    companyName: "HDFC Bank",
    industry: "Banking",
    defaultCity: "Mumbai",
    defaultState: "Maharashtra",
    allowAutoFetch: false,
    isActive: true,
    notes: COMPANY_NOTE,
  },
  {
    name: "ICICI Careers",
    sourceType: "company-career-page",
    fetchMethod: "html",
    sourceUrl: "https://www.icicicareers.com/website/default.aspx",
    companyName: "ICICI Bank",
    industry: "Banking",
    defaultCity: "Mumbai",
    defaultState: "Maharashtra",
    allowAutoFetch: false,
    isActive: true,
    notes: COMPANY_NOTE,
  },
  {
    name: "Axis Bank Careers",
    sourceType: "company-career-page",
    fetchMethod: "html",
    sourceUrl: "https://www.axisbank.com/careers",
    companyName: "Axis Bank",
    industry: "Banking",
    defaultCity: "Mumbai",
    defaultState: "Maharashtra",
    allowAutoFetch: false,
    isActive: true,
    notes: COMPANY_NOTE,
  },
  {
    name: "Kotak Careers",
    sourceType: "company-career-page",
    fetchMethod: "html",
    sourceUrl: "https://www.kotak.com/en/about-us/careers.html",
    companyName: "Kotak Mahindra Bank",
    industry: "Banking",
    defaultCity: "Mumbai",
    defaultState: "Maharashtra",
    allowAutoFetch: false,
    isActive: true,
    notes: COMPANY_NOTE,
  },
  {
    name: "Jio Careers",
    sourceType: "company-career-page",
    fetchMethod: "html",
    sourceUrl: "https://careers.jio.com/",
    companyName: "Reliance Jio",
    industry: "Telecom",
    defaultCity: "Mumbai",
    defaultState: "Maharashtra",
    allowAutoFetch: false,
    isActive: true,
    notes: COMPANY_NOTE,
  },
  {
    name: "Airtel Careers",
    sourceType: "company-career-page",
    fetchMethod: "html",
    sourceUrl: "https://www.airtel.in/careers",
    companyName: "Bharti Airtel",
    industry: "Telecom",
    defaultCity: "Gurugram",
    defaultState: "Haryana",
    allowAutoFetch: false,
    isActive: true,
    notes: COMPANY_NOTE,
  },
  {
    name: "Tata Communications Careers",
    sourceType: "company-career-page",
    fetchMethod: "html",
    sourceUrl: "https://www.tatacommunications.com/careers/",
    companyName: "Tata Communications",
    industry: "Telecom",
    defaultCity: "Mumbai",
    defaultState: "Maharashtra",
    allowAutoFetch: false,
    isActive: true,
    notes: COMPANY_NOTE,
  },
  {
    name: "Mphasis Careers",
    sourceType: "company-career-page",
    fetchMethod: "html",
    sourceUrl: "https://careers.mphasis.com/",
    companyName: "Mphasis",
    industry: "IT Services",
    defaultCity: "Bengaluru",
    defaultState: "Karnataka",
    allowAutoFetch: false,
    isActive: true,
    notes: COMPANY_NOTE,
  },
  {
    name: "Persistent Careers",
    sourceType: "company-career-page",
    fetchMethod: "html",
    sourceUrl: "https://careers.persistent.com/",
    companyName: "Persistent Systems",
    industry: "IT Services",
    defaultCity: "Pune",
    defaultState: "Maharashtra",
    allowAutoFetch: false,
    isActive: true,
    notes: COMPANY_NOTE,
  },
  {
    name: "Coforge Careers",
    sourceType: "company-career-page",
    fetchMethod: "html",
    sourceUrl: "https://careers.coforge.com/home",
    companyName: "Coforge",
    industry: "IT Services",
    defaultCity: "Noida",
    defaultState: "Uttar Pradesh",
    allowAutoFetch: false,
    isActive: true,
    notes: COMPANY_NOTE,
  },
  {
    name: "Genpact Careers",
    sourceType: "company-career-page",
    fetchMethod: "html",
    sourceUrl: "https://www.genpact.com/careers",
    companyName: "Genpact",
    industry: "Business Services",
    defaultCity: "Gurugram",
    defaultState: "Haryana",
    allowAutoFetch: false,
    isActive: true,
    notes: COMPANY_NOTE,
  },
  {
    name: "Join Indian Army",
    sourceType: "government-source",
    fetchMethod: "government",
    sourceUrl: "https://joinindianarmy.nic.in/",
    companyName: "Indian Army",
    industry: "Defence",
    defaultCity: "New Delhi",
    defaultState: "Delhi",
    allowAutoFetch: true,
    isActive: true,
    notes: GOVERNMENT_NOTE,
  },
  {
    name: "Join Indian Navy",
    sourceType: "government-source",
    fetchMethod: "government",
    sourceUrl: "https://www.joinindiannavy.gov.in/",
    companyName: "Indian Navy",
    industry: "Defence",
    defaultCity: "New Delhi",
    defaultState: "Delhi",
    allowAutoFetch: true,
    isActive: true,
    notes: GOVERNMENT_NOTE,
  },
  {
    name: "Indian Air Force Agnipath",
    sourceType: "government-source",
    fetchMethod: "government",
    sourceUrl: "https://agnipathvayu.cdac.in/",
    companyName: "Indian Air Force",
    industry: "Defence",
    defaultCity: "New Delhi",
    defaultState: "Delhi",
    allowAutoFetch: true,
    isActive: true,
    notes: GOVERNMENT_NOTE,
  },
  {
    name: "Meesho Lever Jobs",
    sourceType: "employer-feed",
    fetchMethod: "lever",
    sourceUrl: "https://jobs.lever.co/meesho",
    companyName: "Meesho",
    industry: "E-commerce",
    defaultCity: "Bengaluru",
    defaultState: "Karnataka",
    allowAutoFetch: false,
    isActive: true,
    notes: EMPLOYER_FEED_NOTE,
  },
  {
    name: "Meesho Lever API",
    sourceType: "api-feed",
    fetchMethod: "api",
    sourceUrl: "https://api.lever.co/v0/postings/meesho?mode=json",
    companyName: "Meesho",
    industry: "E-commerce",
    defaultCity: "Bengaluru",
    defaultState: "Karnataka",
    allowAutoFetch: false,
    isActive: true,
    notes: API_FEED_NOTE,
  },
  {
    name: "Postman Greenhouse Jobs",
    sourceType: "employer-feed",
    fetchMethod: "greenhouse",
    sourceUrl: "https://job-boards.greenhouse.io/postman",
    companyName: "Postman",
    industry: "Technology",
    defaultCity: "Bengaluru",
    defaultState: "Karnataka",
    allowAutoFetch: false,
    isActive: true,
    notes: EMPLOYER_FEED_NOTE,
  },
];

export function buildTrustedSourcePackRows(adminUserId: string) {
  return TRUSTED_SOURCE_PACK.slice(0, 100).map((source) => ({
    name: source.name,
    source_type:
      source.sourceType === "government-source"
        ? "official"
        : source.sourceType === "company-career-page" || source.sourceType === "employer-feed"
          ? "employer"
          : "partner",
    transport_type: source.fetchMethod,
    source_url: source.sourceUrl,
    status: source.isActive ? "active" : "paused",
    allow_auto_fetch: source.allowAutoFetch,
    notes: source.notes,
    config: buildJobSourceConfig({
      sourceType: source.sourceType,
      companyName: source.companyName,
      industry: source.industry,
      defaultCity: source.defaultCity,
      defaultState: source.defaultState,
      fetchFrequencyMinutes: source.sourceType === "government-source" ? 360 : 1440,
    }),
    created_by: adminUserId,
    updated_by: adminUserId,
  }));
}
